services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - ${CLOUDBEAVER_DIR}:/opt/cloudbeaver/workspace
    networks:
      - $(NETWORK_NAME)

networks:
  $(NETWORK_NAME):