# bug fix from: https://github.com/HumanSignal/label-studio/issues/3766

services:
    label_studio:
        image: heartexlabs/label-studio:latest
        container_name: label_studio
        ports:
            - 8508:8080
        volumes:
            - ./mydata:/label-studio/data
        env_file:
            - .env
        depends_on:
            - label_studio_postgres_db
        environment:
            - DJANGO_DB=default
            - POSTGRE_NAME=ls
            - POSTGRE_USER=postgres
            - POSTGRE_PASSWORD=postgres
            - POSTGRE_PORT=5432
            - POSTGRE_HOST=label_studio_postgres_db
        command: sh -c "chown -R 1001:root /label-studio/data && label-studio start"

    label_studio_postgres_db:
        image: postgres:latest
        container_name: db
        ports:
            - 5433:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ls

volumes:
    mydata:
    postgres-data: