version: '3'
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9091:9091"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PW}
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9091'      
    volumes:
      - ${MINIO_DIR}:/data
    command: minio server /data