version: '3.7'

services:
    db:
        restart: always
        image: mysql/mysql-server@sha256:5b40d96b11333570143d98d3a74100fefadb9abb17b27a95dbc9ad33544ec142
        container_name: mlflow_db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    web:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
            - db
        ports:
            - "5000:5000"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://localhost:9000
            - AWS_ACCESS_KEY_ID=${MINIO_USER}
            - AWS_SECRET_ACCESS_KEY=${MINIO_PW}
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0

volumes:
    dbdata:



# services:
#   mlflow:
#     image: bitnami/mlflow:latest
#     container_name: mlflow_server
#     environment:
#       - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
#       - MLFLOW_BACKEND_STORE_URI=postgresql://$(PG_USER):$(PG_PASSWORD)@host.docker.internal:5432/
#       - MLFLOW_ARTIFACT_ROOT=s3://mlflow/
#       - AWS_ACCESS_KEY_ID=$(MINIO_ACCESS_KEY)
#       - AWS_SECRET_ACCESS_KEY=$(MINIO_SECRET_KEY)
#       - MLFLOW_S3_ENDPOINT_URL=http://localhost:9000
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./mlruns:/mlflow/mlruns  # Optionnel: stockage local pour les logs et autres métadonnées
