services:
  db-postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PG_LOCAL_DIR}:/var/lib/postgresql/data
    networks:
      - $(NETWORK_NAME)

networks:
  $(NETWORK_NAME):