services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PG_LOCAL_DIR}:/var/lib/postgresql/data